cacheFolder: .yarn/cache

changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "http://npm.haqq.sh"

npmScopes:
  npm:
    npmAuthToken: yRcr2MaVexpigup8O46NCtAPb6OfFKeBlSwenr83ACQ=
    npmRegistryServer: "http://npm.haqq.sh"

unsafeHttpWhitelist:
  - npm.haqq.sh

yarnPath: .yarn/releases/yarn-4.1.1.cjs
