changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

compressionLevel: mixed

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
